apiVersion: v1
kind: Deployment
metadata:
  name: EurekaServer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: EurekaServer
  template:
    metadata:
      labels:
        app: EurekaServer
  spec:
    containers: 
      - name: EurekaServer
        image: reactivestream67/eurekaserver
        ports:
         - name:
           containerPort: 8080
           protocol: Tcp
    